project:
  type: website
  render:
  - "*.qmd"
  - "!CantonKayakClubReport.qmd"
  output-dir: docs/
website:
  google-analytics: 
    tracking-id: "G-J1NMGTKPFE"
  announcement: 
    icon: info-circle
    dismissable: true
    content: "Please see left-sidebar for definitions"
    type: info
    position: below-navbar  
  title: "Current Kayak Conditions - Baltimore, MD"
  navbar:
    logo: images/hex.svg
    left:
    - text: "Home"
      href: index.qmd
    - text: "Assorted Locations"
      menu:
      - text: "Baltimore"
        href: QuartoVersion.qmd
    right:
    - icon: github
      href: https://github.com/DavidRach/BaltimoreKayak
      aria-label: GitHub
  page-footer:
    background: light
    left: Maintained by David Rach
    right: Built with [Quarto](https://quarto.org/).

format:
  html:
    theme: styles.scss